version: '3.4'

services:

    mysql:
        image: mysql
        env_file: ${ENV_MYSQL}
        command: 
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8'
            - '--collation-server=utf8_general_ci'

    confrage:
        build:
            context: ./
            target: local
        env_file: ${ENV_CONFRAGE}
        ports:
            - ${CONRAGE_OUT_PORT}:3000
        # volumes:
            # - ./:/usr/src/app
        command: >
            sh -c "
                dockerize -wait tcp://mysql:3306 -timeout 60s
                npm run start:prod
            "
        depends_on: 
            - mysql