version: '3.4'

services:

    mysql:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: confrage
            MYSQL_USER: confrage
            MYSQL_PASSWORD: confrage
            MYSQL_ROOT_PASSWORD: confrage
        command: 
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8'
            - '--collation-server=utf8_general_ci'

    confrage:
        build: ./
        environment: 
            LOGGER_LEVEL: log,error
            PORT: 3000
            TYPEORM_CONNECTION: mysql
            TYPEORM_HOST: mysql
            TYPEORM_USERNAME: confrage
            TYPEORM_PASSWORD: confrage
            TYPEORM_DATABASE: confrage
            TYPEORM_PORT: 3306
            TYPEORM_ENTITIES: '**/*.entity.js'
            TYPEORM_MIGRATIONS_DIR: migration
            TYPEORM_MIGRATIONS: dist/migration/**/*.js
            STORAGE_DIRECTORY: ~/Downloads
        ports:
            - 80:3000
        volumes: 
            - ./:/usr/src/app
        entrypoint: npm run start:dev
        depends_on: 
            - mysql