version: '3.4'

services:

    mysql:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: confrage
            MYSQL_USER: confrage
            MYSQL_PASSWORD: confrage
            MYSQL_ROOT_PASSWORD: confrage
        command: 
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8'
            - '--collation-server=utf8_general_ci'